name             'sysadmin'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sysadmin'
long_description 'Installs/Configures sysadmin'
version          '0.1.0'
